[workspace]
publish = false        
release_always = true 
pr_labels = ["release"]
custom_major_increment_regex = "a^"
git_tag_enable = true
git_release_enable = true
pr_draft = false


[changelog]
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  {skip = true}
]