[workspace]
publish = false        
release_always = true 
pr_labels = ["release"]
custom_major_increment_regex = "a^"
git_tag_enable = true
git_release_enable = true
pr_draft = false
git_tag_name = "{{ package }}-v{{ version }}"

[changelog]
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = ".*", group = "Other", default_scope = "other" } 
]

[[package]]
name = "crusty_plugin_telegram"
changelog_path = "crates/crusty_plugin_telegram/CHANGELOG.md"
changelog_update = true
publish = false
git_tag_name = "crusty_plugin_telegram-v{{ version }}"

[[package]]
name = "crusty"
changelog_path = "crates/crusty/CHANGELOG.md"
changelog_update = true
publish = false
git_tag_name = "crusty-v{{ version }}"