[workspace]
publish = false        
release_always = true 
allow_major_bump = false
include = ["crates/**"]

[workspace.package_config]
include = [
    "src/**/*",
    "Cargo.toml",
    "plugin.crusty.json"
]


[changelog]
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },

  { message = "^refactor", skip = true },
  { message = "^style", skip = true },
  { message = "^docs", skip = true },
  { message = "^test", skip = true },
  { message = "^chore", skip = true },
  { message = "^ci", skip = true },
]