name: Multi-Plugin Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-pack:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use_cross: false
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            use_cross: false

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_cross: false

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use_cross: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Cross
        if: ${{ matrix.use_cross }}
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Run Build Manager
        shell: bash
        run: |
          CROSS_FLAG=""
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            CROSS_FLAG="--cross"
          fi

          python scripts/build_all.py $CROSS_FLAG --target ${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugins-all-${{ matrix.target }}
          path: "**/dist/*"
